language: objective-c
osx_image: xcode8.3
env:
  global:
  - IOS_FRAMEWORK_SCHEME="OperaSwift-iOS"
  - OSX_FRAMEWORK_SCHEME="OperaSwift-OSX"
  - TVOS_FRAMEWORK_SCHEME="OperaSwift-tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="OperaSwift-watchOS"
  - IOS_SDK=iphonesimulator10.3
  - OSX_SDK=macosx10.12
  - TVOS_SDK=appletvsimulator10.2
  - WATCHOS_SDK=watchsimulator3.2
  matrix:
    - DESTINATION="OS=10.3,name=iPhone 6s"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
    - DESTINATION="arch=x86_64"                     SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"
    - DESTINATION="OS=10.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"
    - DESTINATION="OS=3.2,name=Apple Watch - 42mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK"
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- if [ ${SCHEME} = ${IOS_FRAMEWORK_SCHEME} ]; then ./build_dependencies.sh --platform iOS; fi
- if [ ${SCHEME} = ${OSX_FRAMEWORK_SCHEME} ]; then ./build_dependencies.sh --platform OSX; fi
- if [ ${SCHEME} = ${TVOS_FRAMEWORK_SCHEME} ]; then ./build_dependencies.sh --platform tvOS; fi
- if [ ${SCHEME} = ${WATCHOS_FRAMEWORK_SCHEME} ]; then ./build_dependencies.sh --platform watchOS; fi
script:
- xcodebuild -project OperaSwift.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
    -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c; test ${PIPESTATUS[0]} -eq 0
